# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "XXX"
  lane :ci do
    xcodebuild(
    workspace: "FuckingEnglish.xcworkspace",
    scheme: "FuckingEnglish",
    configuration: "Debug",
    build: true,
    destination: "generic/platform=iOS",
    build_settings: {
      "CODE_SIGNING_REQUIRED" => "NO",
      "CODE_SIGN_IDENTITY" => "",
      "CODE_SIGNING_ALLOWED" => "NO"
    }
  )
  end
end
